baseURL = "https://examplesite.com"
googleAnalytics = ""
theme = "omega"
title = "Xylem Literary Magazine"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "home"
pre = ""
url = "/"
weight = 1
[[menu.main]]
name = "about"
pre = ""
url = "about"
weight = 2
[[menu.main]]
name = "publications"
pre = ""
url = "publications"
weight = 3
[[menu.main]]
name = "how to submit"
pre = ""
url = "howtosubmit"
weight = 4
[[menu.main]]
name = "contact"
pre = ""
url = "contact"
weight = 5
[params]
author = "Themefisher"
contact_info = ""
description = "This is meta description"
logo = "/images/xylem-logo-light-03.png"
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_marker = "images/map-marker.png"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
[[params.social]]
icon = "fa-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "fa-twitter"
link = "#"
title = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "fa-github"
link = "#"
title = "github"
[[params.social]]
icon = "fa-linkedin"
link = "#"
title = "linkedin"
[permalinks]
post = "/about/"
top = "/:filename/"
